version: '3.5'

services:
        frontend:
                image: frontend-example
                ports: 
                - 5000:5000
        backend:
                image: backend-example
                ports: 
                - 8000:8000
