version: '3.5'

services:
        nginx:
                image: jwilder/nginx-proxy
                volumes:
                - /var/run/docker.sock:/tmp/docker.sock:ro 
                - ./nginx.conf:/etc/nginx/nginx.conf
                ports: 
                - 80:80
        frontend:
                image: frontend-example2
                ports: 
                - 5000:5000
        backend:
                image: backend-example2
                ports: 
                - 8000:8000
                environment: 
                - REDIS=redis-db
                - REDIS_PORT=6379
                - DB_USERNAME=postgres
                - DB_PASSWORD=example
                - DB_HOST=db
                depends_on:
                - db
        redis-db:
                image: redis
                ports:
                - 6379:6379
        db:
                image: postgres
                restart: unless-stopped
                environment:
                  POSTGRES_PASSWORD: example

